package com.fatin.fn_canculator;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class Frame extends JFrame implements ActionListener{
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JButton acBtn, addBtn, cBtn, divBtn, dotBtn, eqlBtn, mulBtn, numBtn0, numBtn1, numBtn2, numBtn3, numBtn4, numBtn5, numBtn6, numBtn7, numBtn8, numBtn9, subBtn;
    public JPanel jPanel1;
    public JScrollBar jScrollBar1;
    public JTextField tf;
    
    double num1=0,num2=0,result=0;
    char op;
    // End of variables declaration//GEN-END:variables
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        jScrollBar1 = new JScrollBar();
        jPanel1 = new JPanel();
        acBtn = new JButton();
        tf = new JTextField();
        cBtn = new JButton();
        addBtn = new JButton();
        subBtn = new JButton();
        numBtn1 = new JButton();
        numBtn2 = new JButton();
        numBtn3 = new JButton();
        numBtn0 = new JButton();
        dotBtn = new JButton();
        eqlBtn = new JButton();
        numBtn4 = new JButton();
        numBtn5 = new JButton();
        numBtn6 = new JButton();
        mulBtn = new JButton();
        numBtn8 = new JButton();
        numBtn9 = new JButton();
        numBtn7 = new JButton();
        divBtn = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("FN Calculator");
        setFont(new Font("Arial", 1, 10)); // NOI18N
        setName("fr"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new Color(0, 0, 0));

        acBtn.setBackground(new Color(200, 0, 54));
        acBtn.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        acBtn.setForeground(new Color(0, 0, 0));
        acBtn.setText("AC");
        acBtn.setBorderPainted(false);
        acBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        acBtn.setFocusable(false);
        acBtn.addActionListener(this);

        tf.setBackground(new Color(36, 36, 36));
        tf.setFont(new Font("Segoe UI", 1, 24)); // NOI18N
        tf.setForeground(new Color(255, 255, 255));
        tf.setBorder(null);
        tf.setCursor(new Cursor(Cursor.TEXT_CURSOR));

        cBtn.setBackground(new Color(200, 0, 54));
        cBtn.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        cBtn.setForeground(new Color(0, 0, 0));
        cBtn.setText("C");
        cBtn.setBorderPainted(false);
        cBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        cBtn.setFocusable(false);
        cBtn.addActionListener(this);

        addBtn.setBackground(new Color(255, 219, 0));
        addBtn.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        addBtn.setForeground(new Color(0, 0, 0));
        addBtn.setText("+");
        addBtn.setBorderPainted(false);
        addBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        addBtn.setFocusable(false);
        addBtn.addActionListener(this);

        subBtn.setBackground(new Color(255, 219, 0));
        subBtn.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        subBtn.setForeground(new Color(0, 0, 0));
        subBtn.setText("-");
        subBtn.setFocusable(false);
        subBtn.addActionListener(this);

        numBtn1.setBackground(new Color(36, 36, 36));
        numBtn1.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        numBtn1.setForeground(new Color(255, 255, 255));
        numBtn1.setText("1");
        numBtn1.setBorderPainted(false);
        numBtn1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        numBtn1.setFocusable(false);
        numBtn1.addActionListener(this);

        numBtn2.setBackground(new Color(36, 36, 36));
        numBtn2.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        numBtn2.setForeground(new Color(255, 255, 255));
        numBtn2.setText("2");
        numBtn2.setBorderPainted(false);
        numBtn2.setFocusable(false);
        numBtn2.addActionListener(this);    

        numBtn3.setBackground(new Color(36, 36, 36));
        numBtn3.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        numBtn3.setForeground(new Color(255, 255, 255));
        numBtn3.setText("3");
        numBtn3.setBorderPainted(false);
        numBtn3.setCursor(new Cursor(Cursor.HAND_CURSOR));
        numBtn3.setFocusable(false);
        numBtn3.addActionListener(this);

        numBtn0.setBackground(new Color(36, 36, 36));
        numBtn0.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        numBtn0.setForeground(new Color(255, 255, 255));
        numBtn0.setText("0");
        numBtn0.setBorderPainted(false);
        numBtn0.setCursor(new Cursor(Cursor.HAND_CURSOR));
        numBtn0.setFocusable(false);
        numBtn0.addActionListener(this);

        dotBtn.setBackground(new Color(36, 36, 36));
        dotBtn.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        dotBtn.setForeground(new Color(255, 255, 255));
        dotBtn.setText(".");
        dotBtn.setBorderPainted(false);
        dotBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        dotBtn.setFocusable(false);
        dotBtn.addActionListener(this);

        eqlBtn.setBackground(new Color(255, 219, 0));
        eqlBtn.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        eqlBtn.setForeground(new Color(0, 0, 0));
        eqlBtn.setText("=");
        eqlBtn.setBorderPainted(false);
        eqlBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        eqlBtn.setFocusable(false);
        eqlBtn.addActionListener(this);

        numBtn4.setBackground(new Color(36, 36, 36));
        numBtn4.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        numBtn4.setForeground(new Color(255, 255, 255));
        numBtn4.setText("4");
        numBtn4.setBorderPainted(false);
        numBtn4.setCursor(new Cursor(Cursor.HAND_CURSOR));
        numBtn4.setFocusable(false);
        numBtn4.addActionListener(this);

        numBtn5.setBackground(new Color(36, 36, 36));
        numBtn5.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        numBtn5.setForeground(new Color(255, 255, 255));
        numBtn5.setText("5");
        numBtn5.setBorderPainted(false);
        numBtn5.setCursor(new Cursor(Cursor.HAND_CURSOR));
        numBtn5.setFocusable(false);
        numBtn5.addActionListener(this);

        numBtn6.setBackground(new Color(36, 36, 36));
        numBtn6.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        numBtn6.setForeground(new Color(255, 255, 255));
        numBtn6.setText("6");
        numBtn6.setBorderPainted(false);
        numBtn6.setCursor(new Cursor(Cursor.HAND_CURSOR));
        numBtn6.setFocusable(false);
        numBtn6.addActionListener(this);

        mulBtn.setBackground(new Color(255, 219, 0));
        mulBtn.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        mulBtn.setForeground(new Color(0, 0, 0));
        mulBtn.setText("*");
        mulBtn.setBorderPainted(false);
        mulBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        mulBtn.setFocusable(false);
        mulBtn.addActionListener(this);

        numBtn8.setBackground(new Color(36, 36, 36));
        numBtn8.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        numBtn8.setForeground(new Color(255, 255, 255));
        numBtn8.setText("8");
        numBtn8.setBorderPainted(false);
        numBtn8.setCursor(new Cursor(Cursor.HAND_CURSOR));
        numBtn8.setFocusable(false);
        numBtn8.addActionListener(this);

        numBtn9.setBackground(new Color(36, 36, 36));
        numBtn9.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        numBtn9.setForeground(new Color(255, 255, 255));
        numBtn9.setText("9");
        numBtn9.setBorderPainted(false);
        numBtn9.setCursor(new Cursor(Cursor.HAND_CURSOR));
        numBtn9.setFocusable(false);
        numBtn9.addActionListener(this);

        numBtn7.setBackground(new Color(36, 36, 36));
        numBtn7.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        numBtn7.setForeground(new Color(255, 255, 255));
        numBtn7.setText("7");
        numBtn7.setBorderPainted(false);
        numBtn7.setCursor(new Cursor(Cursor.HAND_CURSOR));
        numBtn7.setFocusable(false);
        numBtn7.addActionListener(this);

        divBtn.setBackground(new Color(255, 219, 0));
        divBtn.setFont(new Font("Segoe UI", 1, 30)); // NOI18N
        divBtn.setForeground(new Color(0, 0, 0));
        divBtn.setText("/");
        divBtn.setBorderPainted(false);
        divBtn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        divBtn.setFocusable(false);
        divBtn.addActionListener(this);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numBtn0, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(dotBtn, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(eqlBtn, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf, GroupLayout.PREFERRED_SIZE, 330, GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numBtn7, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(numBtn8, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(numBtn9, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(divBtn, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numBtn4, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(numBtn5, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(numBtn6, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(mulBtn, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(numBtn1, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(numBtn2, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(numBtn3, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(acBtn, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(cBtn, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addBtn, GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(subBtn, GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(tf, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(acBtn, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBtn, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(numBtn1, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(numBtn2, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(numBtn3, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(subBtn, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(numBtn4, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(numBtn5, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(numBtn6, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(mulBtn, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(numBtn7, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(numBtn8, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(numBtn9, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(divBtn, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(numBtn0, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(dotBtn, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE)
                    .addComponent(eqlBtn, GroupLayout.PREFERRED_SIZE, 65, GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==numBtn0) {
            tf.setText(tf.getText().concat("0"));
        }
        if(e.getSource()==numBtn1) {
            tf.setText(tf.getText().concat("1"));
        }
        if(e.getSource()==numBtn2) {
            tf.setText(tf.getText().concat("2"));
        }
        if(e.getSource()==numBtn3) {
            tf.setText(tf.getText().concat("3"));
        }
        if(e.getSource()==numBtn4) {
            tf.setText(tf.getText().concat("4"));
        }
        if(e.getSource()==numBtn5) {
            tf.setText(tf.getText().concat("5"));
        }
        if(e.getSource()==numBtn6) {
            tf.setText(tf.getText().concat("6"));
        }
        if(e.getSource()==numBtn7) {
            tf.setText(tf.getText().concat("7"));
        }
        if(e.getSource()==numBtn8) {
            tf.setText(tf.getText().concat("8"));
        }
        if(e.getSource()==numBtn9) {
            tf.setText(tf.getText().concat("9"));
        }
        if(e.getSource()==dotBtn) {
            tf.setText(tf.getText().concat("."));
        }
        if(e.getSource()==addBtn) {
            num1 = Double.parseDouble(tf.getText());
            tf.setText("");
            op='+';
        }
        if(e.getSource()==subBtn) {
            num1 = Double.parseDouble(tf.getText());
            tf.setText("");
            op='-';
        }
        if(e.getSource()==mulBtn) {
            num1 = Double.parseDouble(tf.getText());
            tf.setText("");
            op='*';
        }
        if(e.getSource()==divBtn) {
            num1 = Double.parseDouble(tf.getText());
            tf.setText("");
            op='/';
        }
        if(e.getSource()==eqlBtn) {
            num2 = Double.parseDouble(tf.getText());
            switch(op) {
                case '+':
                    result = num1+num2;
                    break;
                case '-':
                    result = num1-num2;
                    break;
                case '*':
                    result = num1*num2;
                    break;
                case '/':
                    result = num1/num2;
                    break;
            }
            tf.setText(String.valueOf(result));
            num1 = result;
            num2 = 0;
        }
        if(e.getSource()==cBtn) {
            String s=tf.getText();
            tf.setText("");
            for(int i=0;i<s.length()-1;i++) {
                tf.setText(tf.getText()+s.charAt(i));
            }
        }
        if(e.getSource()==acBtn) {
            tf.setText("");
            num1 = num2 = result = 0;
        }
    }
}